name: Deploy Status Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm cache clean --force || true
        rm -rf node_modules package-lock.json || true
        npm install --verbose
        echo "Verifying installation..."
        ls -la node_modules/.bin/ | grep next || echo "Next.js binary not found"
        
    - name: Run build
      run: |
        echo "Building with Next.js..."
        if [ -f "node_modules/.bin/next" ]; then
          node_modules/.bin/next build
        else
          npx --yes next@15.1.7 build
        fi
      
    - name: Run lint
      run: |
        if [ -f "node_modules/.bin/next" ]; then
          node_modules/.bin/next lint --fix || echo "Lint issues found but continuing..."
        else
          npx --yes next@15.1.7 lint --fix || echo "Lint issues found but continuing..."
        fi
      
    - name: Check build output
      run: |
        echo "Build completed successfully"
        ls -la .next/
        
    - name: Deploy status notification
      run: |
        echo "✅ Build successful on commit: ${{ github.sha }}"
        echo "🚀 Ready for Vercel deployment"

  deployment-check:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Wait for deployment (poll)
      run: |
        echo "Polling Vercel deployment status..."
        for i in {1..15}; do
          response=$(curl -s -o /dev/null -w "%{http_code}" https://kakomonn-com.vercel.app/)
          echo "Check $i/15: HTTP $response"
          if [ "$response" -eq 200 ]; then
            echo "✅ Deployment successful - Site is live!"
            echo "🌐 URL: https://kakomonn-com.vercel.app"
            exit 0
          fi
          echo "⏳ Waiting for deployment... ($i/15)"
          sleep 20
        done
        echo "❌ Timeout: deployment not live after 5 minutes"
        exit 1
        
    - name: Check all pages
      run: |
        echo "Testing all pages..."
        
        # Test main page
        main_status=$(curl -s -o /dev/null -w "%{http_code}" https://kakomonn-com.vercel.app/)
        echo "Main page: HTTP $main_status"
        
        # Test threads page  
        threads_status=$(curl -s -o /dev/null -w "%{http_code}" https://kakomonn-com.vercel.app/threads)
        echo "Threads page: HTTP $threads_status"
        
        # Test thread detail page
        detail_status=$(curl -s -o /dev/null -w "%{http_code}" https://kakomonn-com.vercel.app/threads/1)
        echo "Thread detail: HTTP $detail_status"
        
        # Test upload page
        upload_status=$(curl -s -o /dev/null -w "%{http_code}" https://kakomonn-com.vercel.app/upload)
        echo "Upload page: HTTP $upload_status"
        
        # Check if all pages are working
        if [ $main_status -eq 200 ] && [ $threads_status -eq 200 ] && [ $detail_status -eq 200 ] && [ $upload_status -eq 200 ]; then
          echo "✅ All pages are working correctly!"
        else
          echo "❌ Some pages have issues"
          exit 1
        fi